#define MAX_ROOM_COUNT              @MAX_ROOM_COUNT@
#define MAX_ROOM_PLAYER_COUNT       @MAX_ROOM_PLAYER_COUNT@
#define MAX_ROOM_SPECTATOR_COUNT    @MAX_ROOM_SPECTATOR_COUNT@
#define MAX_ROOM_NAME_COUNT         @MAX_ROOM_NAME_COUNT@
#define MAX_ROOM_PW                 @MAX_ROOM_PW@
#define MAX_ROOM_MEM_COUNT          (@MAX_ROOM_PLAYER_COUNT@ + @MAX_ROOM_SPECTATOR_COUNT@)

#define MAX_PLAYER_NAME_COUNT       @MAX_PLAYER_NAME_COUNT@
#define MAX_GLOBAL_PLAYER_COUNT     ((@MAX_ROOM_PLAYER_COUNT@ + @MAX_ROOM_SPECTATOR_COUNT@) * @MAX_ROOM_COUNT@)
#define MAX_SKILL_COUNT             @MAX_SKILL_COUNT@